- name: Set up of catalogue server
  hosts: localhost
  connection: ssh
  become: yes
  tasks:
  - name: Disable NodeJS
    ansible.builtin.command:
      cmd: dnf module disable nodejs -y

  - name: Enable nodejs 20
    ansible.builtin.command:
      cmd: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: present

  - name: checking user exist or not 
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
 
  - when: output.rc != 0
    name: creating user roboshop
    become: yes
    ansible.builtin.user:
      name: roboshop
      state: present
  
  - name: checking dir exist or not
    ansible.builtin.stat:
      path: /root/app
    register: output
 
  - when: output.stat.exists != true
    name: "Creating  /app"
    ansible.builtin.file:
      path: /root/app
      state: directory

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  - name: unzip the artifact
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
  - name: installing dependencies under /app directory
    ansible.builtin.command: 
      cmd: npm install
      chdir: /app
  - name: Copy catalogue repo
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service 
  
  
    
    

  