- name: setup mysql
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Copy mysql repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    - name: Install mysql
      ansible.builtin.yum:
        name: mysql-community-server
        state: present
    - name: enable and start mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes