- name: setup shipping service
  hosts: shipping
  connection: ssh
  become: yes

  tasks:
  - name: install java 17
    ansible.builtin.yum:
      name: java-17-openjdk-devel
      state: present
  - name: install maven
    ansible.builtin.yum:
      name: maven
      state: present


  - name: check roboshop user exist or not
    ansible.builtin.command:
      cmd: id roboshop
    register: output
    ignore_errors: true
  - when: output.rc != 0
    name: creating user roboshop
    ansible.builtin.user:
      name: roboshop
      state: present


  - name: checking dir exist or not
    ansible.builtin.stat:
      path: /app
    register: output

 
  - when: output.stat.exists != true
    name: "Creating  /app"
    ansible.builtin.file:
      path: /app
      state: directory

  
  - name: Download application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp/shipping.zip


  - name: Unzip artifact
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app


  - name: install dependencies
    ansible.builtin.command:
      cmd: mvn clean package
      chdir: /app


  - name: Rename file using command module
    ansible.builtin.command:
      cmd: mv target/shipping-1.0.jar shipping.jar


  - name: Daemon reload and start service
    ansible.builtin.systemd_service:
      name: cart
      daemon_reload: true
      enabled: yes
      state: started


  - name: Install mysql
    ansible.builtin.yum:
      name: mysql
      state: present


  - name: Load shipping database schema
    ansible.builtin.shell:
      cmd: mysql -h mysql.roboshopservice.store -uroot -pRoboShop@1 < /app/schema/shipping.sql


  - name: Restart shipping service
    ansible.builtin.service:
      name: shipping
      state: restarted
