- name: Set up of user server
  hosts: user
  connection: ssh
  become: yes
  tasks:
  - name: Disable NodeJS
    ansible.builtin.command:
      cmd: dnf module disable nodejs -y

  - name: Enable nodejs 20
    ansible.builtin.command:
      cmd: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: present

  - name: checking user exist or not 
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
 
  - when: output.rc != 0
    name: creating user roboshop
    become: yes
    ansible.builtin.user:
      name: roboshop
      state: present
  
  - name: checking dir exist or not
    ansible.builtin.stat:
      path: /app
    register: output
 
  - when: output.stat.exists != true
    name: "Creating  /app"
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: unzip the artifact
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app

  - name: installing dependencies under /app directory
    ansible.builtin.command: 
      cmd: npm install
      chdir: /app

  - name: Copy user repo
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service 

  - name: Daemon reload and start service
    ansible.builtin.systemd_service:
      name: user
      daemon_reload: true
      enabled: yes
      state: started

  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongodb-org-7.0.repo

  - name: Install mongodb client
    ansible.builtin.yum:
      name: mongodb-mongosh
      state: present

  - name: Loading schema
    ansible.builtin.shell:
      cmd: mongosh --host 172.31.0.228 < /app/schema/user.js
  
    
    

  